name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/myhome/codes/My_Home
            git pull
            poetry install --no-interaction --no-ansi  
            poetry config virtualenvs.in-project true
            poetry shell
            .venv\Scripts\activate
            poetry run pm2 restart backend
