# write a github action that on push to the main branch it ssh into my server, cd into the project directory, git pull and restart the uvicorn server.

name: Deploy
on:
  push:
    branches:
      - main


jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Setup SSH
          uses: appleboy/ssh-action@master
          with:
                username: ${{ secrets.SSH_USER }}
                host: ${{ secrets.SSH_HOST }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: 22    
                script: |
                    cd /home/myhome/codes/My_Home
                    git pull
                    poetry install
                    pm2 restart backend