name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/myhome/codes/My_Home
            git pull
            source $HOME/.poetry/env  # Activate Poetry environment variables
            poetry install --no-interaction --no-ansi  # Install dependencies
            pm2 restart backend
